- recipe/meta.yaml
> Remove cudatoolkit-dev from recipe

- recipe/0102-Fixed-failure-on-baremetal.patch
- recipe/build.sh
- recipe/meta.yaml
Fixes build failure on baremetal.
> Fix on baremetal

- recipe/build.sh
- recipe/meta.yaml
- tests/open-ce-tests.yaml
Added initial tests for torchvision. This is part of the work done in open-ce/open-ce#145.
The version currently being stored in torchvision.__version__ is 0.7.0a0, which is not correct. Setting BUILD_VERSION will set the value correctly.
> Add initial tests

- recipe/0101-find-ffmpeg-in-conda-env.patch
- recipe/0102-Fixed-failure-on-baremetal.patch
- recipe/meta.yaml
- tests/open-ce-tests.yaml
- variants/meta.yaml
Fixes https://github.com/open-ce/open-ce/issues/168.
> updates for v0.8.2

- recipe/meta.yaml
Fixes https://github.com/open-ce/open-ce/issues/221.
> add jpeg support

- recipe/meta.yaml
- tests/open-ce-tests.yaml
> skip additional tests that fail

- recipe/build.sh
- recipe/meta.yaml
- tests/open-ce-tests.yaml
Fixes:
- Tests failure at setup stage on M4-2 with the error - `git: command not found.`
- Tests failure with error `RuntimeError: decodeJPEG: torchvision not compiled with libjpeg support`  on baremetal. This was reported by @npanpaliya.  
> install git for tests

- recipe/meta.yaml
patch is not available on M4-1 and hence builds fail, so adding it as a build time dependency. 
> add patch as build time dependency

- variants/meta.yaml
Handles open-ce/open-ce#280 for TorchVision.
> Add python dependency to meta-package

- recipe/meta.yaml
Without the build time dependency on a cudatoolkit version, the wrong build of pytorch could be pulled in.
> Add cuda dep

- variants/meta.yaml
Fixes https://github.com/open-ce/open-ce/issues/322.
> update license information

- tests/open-ce-tests.yaml
Fixes the following error observed during test execution:
`E           RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install..`
3. If any …
> fix pytorch torchvision version mismatch error during tests execution

- recipe/0101-find-ffmpeg-in-conda-env.patch
- recipe/0102-Fixed-failure-on-baremetal.patch
- recipe/0103-pick-up-ancaconda-gcc.patch
- recipe/meta.yaml
- tests/open-ce-tests.yaml
- variants/meta.yaml
Fixes https://github.com/open-ce/open-ce/issues/265.
> [1.3] refresh to v0.9.1

- recipe/0102-Fixed-failure-on-baremetal.patch
- recipe/meta.yaml
- variants/meta.yaml
> refresh to v0.10.0

- recipe/meta.yaml
> refresh to v0.10.1

- recipe/0101-find-ffmpeg-in-conda-env.patch
- recipe/meta.yaml
- tests/open-ce-tests.yaml
- variants/meta.yaml
> refresh to v0.11.1

- recipe/meta.yaml
- variants/meta.yaml
Refresh to v0.11.2 - https://github.com/open-ce/open-ce/issues/570
> refresh to v0.11.2

- recipe/meta.yaml
- variants/meta.yaml
> [main] refresh to v0.11.2 (#35)

- recipe/meta.yaml
- tests/open-ce-tests.yaml
- variants/meta.yaml
- Refresh to v0.11.3
- remove pillow pin
- add test block
https://github.com/open-ce/open-ce/issues/584
> [1.5] refresh to v0.11.3

- recipe/meta.yaml
- tests/open-ce-tests.yaml
- variants/meta.yaml
> port changes from 1.5 branch

- tests/open-ce-tests.yaml
> skip test_url_is_accessible test as some URLs are broken

- vision-0.13/recipe/meta.yaml
> do not use Anaconda GCC for P10

- vision-0.13/recipe/meta.yaml
- vision-0.13/variants/meta.yaml
> refresh to v0.13.1

- vision-0.14/recipe/meta.yaml
- vision-0.14/variants/meta.yaml
> refresh to v0.14.1

- recipe/meta.yaml
> fix build on P10

- vision-0.15/recipe/meta.yaml
- vision-0.15/variants/meta.yaml
> refresh to v0.15.2
